### ISSUE TITLE
Review & Feedback 

### ISSUE THREAD

**Issue by sara219** [ahmadfarid-059/first-rebo#1]
## Great Job Ahmad :boom:

you did a great job so far during the course 

**overall feedback**, you hit all the goals for the first two weeks. 
Keep up with your good work :muscle:

-- follow up for code review :point_down:

**Comment by sara219** [comment]
## Assignment Review

- **when you are going to give the element a class make it descriptive and suitable for the content.**
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/assign.html#L15


- **it's better to use semantic element** 
_ex: use `section` or `main` instead of `div`_
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/assign.html#L13

- **To make your code readable, every element should start within a new line (make your code cleaner and readable**
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/assign.html#L19

- if you want to give more than one class name to an element, no need to use `,`
_ex: `'box greenBox'`_
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/assign.html#L14

**Comment by sara219** [comment]
## Cont. Assignment Review


- **you don't need text-align since you're using flexbox** (flexbox will do everything you need)
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/style4.css#L21

- **use `  justify-content: space-around;` instead of `center` to make space between the images**
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/style4.css#L10

- **Unnecessary code**, try to remove it, nothing will be change
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/style4.css#L20

- if you change to space-around as I mention in the first point, no need for this
https://github.com/ahmadfarid-059/first-rebo/blob/2051a6c8e7175bbfc58dd14e4087e7d4292b8ef8/style4.css#L48-L50

- what will happen if I make the screen smaller, try to do the `wrap` thing using flexbox

**Comment by sara219** [comment]
## Clean Code: 

try to make your code clean and readable
  * remove white space 
  * be sure the selectors start from the same point, the same for the rest of the rule set 
  * write a descriptive comment to explain your code 

![Screenshot from 2021-02-26 16-37-21](https://user-images.githubusercontent.com/47992412/109313822-4e85ae80-7851-11eb-8742-6ac48393885f.png)


**CLEANER**

![Screenshot from 2021-02-26 16-37-35](https://user-images.githubusercontent.com/47992412/109313871-59d8da00-7851-11eb-8807-6baeba25ed39.png)

**Comment by ahmadfarid-059** [comment]
Thank you mrs Sara for that descriptive review and I will get some points more clear to you.
Firstly, I thought that to make the page looks like a box I should put my elements into divs. 
In flex box: some values didn't work with me, so that made me try every single value to reach that result.  
Thank YOU
